### ISSUE TITLE
CMS Site Content Accessing pages

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#18] opened 2016-02-03 10:15 UTC
Not sure what the correct behaviour is supposed to be but the url to a page in the content listing has a /cms in it and is going to 'page not found'
![capture](https://cloud.githubusercontent.com/assets/11847651/12779273/fc0f93c8-ca5e-11e5-8336-255e309af808.PNG)

**Comment by asimshah** [comment] 2016-02-04 04:06
I am not able to reproduce this. I tried using dwh.test.webframe.co.uk this morning and while I do get the image error - the icon for a page is not being found - the page link is correct and works
Given that I am using the same test site as you, there has to be some context that is different. Please try again and see if you can isolate this context: browser?, o/s?, etc.

**Comment by asimshah** [comment] 2016-02-04 04:53
I have now reproduced this problem - the links are correct in Chrome but not in IE. Fix will rollout with the next upgrade.

**Comment by mikebattye** [comment] 2016-02-04 12:20
Sorry, I should have said I was using Microsoft Edge.

**Comment by mikebattye** [comment] 2016-02-04 14:03
Doesn't work in Firefox (44.0) either.

**Comment by mikebattye** [comment] 2016-02-25 13:11
Just to report that it is not working on Chrome now either. I can work round it by going to pages directly with their url so no need to rush to fix.

**Comment by asimshah** [comment] 2016-02-25 14:17
If you read my comment on closing, you will get this fix with the next version whenever that it! That is why I closed It!

**Closed** 2016-04-06 16:34 UTC
